Controllers/ExploreController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using P1WebMVC.Data;
using P1WebMVC.Interfaces;
using P1WebMVC.Middlewares;
using P1WebMVC.Models;
using P1WebMVC.Models.ViewModels;

namespace P1WebMVC.Controllers
{
    public class ExploreController : Controller
    {
        // GET: ExploreController

        private readonly SqlDbContext dbContext;


        public ExploreController(SqlDbContext dbContext)
        {
            this.dbContext = dbContext;

        }

        // attribute flag 

        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            try
            {
                var posts = await dbContext.Posts
                .Include(posts => posts.Comments).ThenInclude(comment => comment.User)
                .Include(posts => posts.Likes)
                // .Where(posts => posts.PostpicURL != null)
                .ToListAsync();

                var exploreViewModel = new ExploreViewModel
                {
                    Posts = posts,
                    LoggedInUser = HttpContext.Items["user"] as User
                };

                // DTO
                return View(exploreViewModel);
            }
            catch (System.Exception)
            {
                throw;
            }
        }


        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Reels()
        {
            try
            {
                var posts = await dbContext.Posts
                .Include(posts => posts.Comments).ThenInclude(comment => comment.User)
                .Include(posts => posts.Likes)
                .Where(posts => posts.PostVideoURL != null)
                .ToListAsync();

                var exploreViewModel = new ExploreViewModel
                {
                    Posts = posts,
                    LoggedInUser = HttpContext.Items["user"] as User
                };

                // DTO
                return View(exploreViewModel);
            }
            catch (System.Exception)
            {
                throw;
            }
        }


        [Authorize]
        [HttpGet]
        public async Task<ActionResult> Profile(Guid userId)
        {
            try
            {
                var posts = await dbContext.Posts
                .Include(posts => posts.Comments).ThenInclude(comment => comment.User)
                .Include(posts => posts.Likes)
                .Where(post => post.UserId == userId)
                .ToListAsync();

                var profileUser = await dbContext.Users.FindAsync(userId);
                var users = await dbContext.Users.Where(user => user.Posts.Count > 1).ToListAsync();

                var exploreViewModel = new ExploreViewModel
                {
                    Posts = posts,
                    LoggedInUser = HttpContext.Items["user"] as User,
                    ProfileUser = profileUser,
                    SuggestedUsers = users
                };

                return View(exploreViewModel);
            }
            catch (System.Exception)
            {
                throw;
            }
        }
    }
}

Views/Shared/RightSideNav.cshtml
@model P1WebMVC.Models.ViewModels.ExploreViewModel


<style>
.right_profile_nav {

        width: 20%;
        display: flex;
        flex-direction: column;
        align-items: center;
        font-family: Arial, Helvetica, sans-serif;
        position: fixed;
        right: 20px;
        top: 10px;
        box-shadow: 2px 2px 10px 10px rgba(0, 0, 0, 0.111);
        border-radius: 8px;


        .profile_pic {
        width: 60px;
        height: 60px;
        border-radius: 50%;
        border: 1px solid black;
        margin-top: 30px;
    }

    .username {
        font-weight: 700;
        margin: 5px 0px;
    }

    .userid {
        margin: 5px 0px;
    }

    .location {
        color: grey;
    }

    .user_stats{
        display: flex;
          gap: 30px;
          margin-top: 20px;

        div{
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 5px; 

            span:first-child{
                  font-weight: 700;
            }

            span:last-child{
                    color: grey;
            }

        }
    }

    .about_me{
        padding: 30px;
        h3{
            margin: 0;
            margin-bottom: 10px;
        }
        span{
            color: grey;
        }

        span:last-child{
            color: black;
            cursor: pointer;
        }
    }

    .story_highlights{
        display: flex;
        gap: 10px;

        .story{
            width: 60px;
            height: 60px;
            border-radius: 50%;
            border: 1px solid black ;
        }
    }

    .contact_info{
        width: 90%;
        padding: 20px;
        margin-top: 80px;


        div{
            display: flex;
            flex-direction: column;
            margin-bottom: 20px;

            span:first-child{
                font-weight: 700;
                margin-bottom: 10px;
            }

            span:last-child{
                color: grey;
            }

        }
    }

}
</style>


        <div class="right_profile_nav">

            <img class="profile_pic" src="" alt="profileimage" />

            <div class="username"> @Model?.LoggedInUser?.Username </div>
            <div class="userid"> UserId</div>
            <div class="location"> Sringar , j & k  </div>


            <div class="user_stats">

                <div>
                    <span> @Model?.LoggedInUser?.Posts.Count </span> <span> Posts </span>
                </div>

                <div>
                    <span> 12.7 K </span> <span> Followers </span>
                </div>

                <div>
                    <span>221</span> <span> Following </span>
                </div>

            </div>

            <div class="about_me">

                <h3> About me</h3>
                <span> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error labore nisi nobis autem,
                    voluptatem quod qui arccto odio </span>
                <span> Read more ....</span>

            </div>

            <div class="story_highlights">

                <div class="story">
                    <img src="" alt="story" />
                </div>

                  <div class="story">
                    <img src="" alt="story" />
                </div>

                  <div class="story">
                    <img src="" alt="story" />
                </div>

                  <div class="story">
                    <img src="" alt="story" />
                </div>


            </div>

            <div class="contact_info">

               <h3>  Contact Details</h3>

                <div>
                    <span> Phone number</span>
                    <span> +2345678909</span>
                </div>

                <div>
                    <span> Email Address</span>
                    <span> @Model?.LoggedInUser?.Email </span>
                </div>

                <div>
                    <span> Website </span>
                    <span> www.slothUi.com </span>
                </div>


            </div>

        </div>

Views/Shared/SideNav.cshtml
@model P1WebMVC.Models.ViewModels.ExploreViewModel


<style>
    .side_nav {
        width: 20%;
        padding: 20px;
        position: fixed;
        left : 20px;
        top : 10px;
        box-shadow: 2px 2px 10px 10px rgba(0, 0, 0, 0.111);
        border-radius: 8px;
    
        .brand_name {
            display: flex;
            margin-bottom: 30px;
            h3 {
                font-family: Arial, Helvetica, sans-serif;
                color: rgb(57, 52, 111);
                font-weight: 700;
            }
        }

        .search_bar {
            border: 1px solid rgb(57, 52, 111);
            border-radius: 15px;
            padding: 5px 10px;
            display: flex;
            align-items: center;
            i {
                color: rgb(111, 107, 107);
            }
            input {
                border: none;
                font-size: 16px;
                width: 80%;
                margin-left: 10px;
                outline: none;
            }
        }

        .nav_links {
            margin-top: 40px;
            ul {
                list-style-type: none;
                padding: 0px;
                li {
                    margin: 20px 0px;
                    i {
                        font-size: 22px;
                        padding-left: 15px;
                        color: rgb(111, 107, 107);
                    }
                    a {
                        font-size: 16px;
                        font-family: Arial, Helvetica, sans-serif;
                        color: rgb(59, 59, 59);
                        padding-left: 10px;
                        font-weight: 600;
                        text-decoration: none;
                    }
                }
            }
        }

        .notification_bar {
            /* border: 1px solid black; */
            padding: 10px;
            min-height: 100px;
            border-radius: 15px;
            margin-top: 100px;
            box-shadow: 2px 2px 10px 10px rgba(0, 0, 0, 0.102);
        }

        .logout_tab {
            padding: 10px;
            min-height: 60px;
            border-radius: 15px;
            margin-top: 50px;
            box-shadow: 2px 2px 10px 10px rgba(0, 0, 0, 0.102);
        }
    }
</style>


<div class="side_nav">

    <div class="brand_name">
        <i class="bi bi-stars me-2"></i>    <h3> Trinkle Buddies</h3>
    </div>

    <div class="search_bar">

        <i class="bi bi-search"></i>
        <input placeholder="search" />
    </div>


    <div class="nav_links">
        <ul>
            <li> <i class="bi bi-house-door"></i> <a href="/explore/index"> Explore </a> </li>
            <li> <i class="bi bi-list-task"></i> <a> Followers </a> </li>
            <li> <i class="bi bi-people"></i> <a> Following </a> </li>
            <li> <i class="bi bi-box"></i> <a asp-action="Profile" asp-controller="Explore" asp-route-userId = "@Model?.LoggedInUser.UserId"> Profile </a> </li>
            <li> <i class="bi bi-credit-card"></i> <a>Subscriptions </a> </li>
            <li> <i class="bi bi-gear"></i> <a>Settings </a> </li>
            <li> <i class="bi bi-chat-dots"></i> <a> Help and support </a> </li>
        </ul>
    </div>

    <div class="notification_bar">
        here we will display notifications
    </div>

    <div class="logout_tab">
        here we will display logout options
    </div>

</div>

Views/Shared/Stories.cshtml
<style>
    .stories {

       background:#fff;
        border-radius:3px; 
        box-shadow:2px 2px 10px 10px rgba(0,0,0,0.08);
        height: 100px;

        margin: 15px auto;
        padding: 20px;
        display: flex;
        align-items: center;
        gap: 20px;

        .story {

            width: 80px;
            height: 80px;
            border: 3px solid rgb(16, 212, 16);
            border-radius: 50%;

            img {
                width: 100%
            }

        }


    }
</style>





<div class="stories">


    <div class="story">
        <img src="https://cdn-icons-png.flaticon.com/512/3135/3135715.png" alt="">
    </div>

    <div class="story">
        <img src="https://cdn-icons-png.flaticon.com/512/3135/3135715.png" alt="">
    </div>

    <div class="story">
        <img src="https://cdn-icons-png.flaticon.com/512/3135/3135715.png" alt="">
    </div>


</div>

Views/Shared/SuggestionPartial.cshtml
@model P1WebMVC.Models.ViewModels.ExploreViewModel


<style>
    .suggestions {
        width: 20%;
        font-family: Arial, Helvetica, sans-serif;
        position: fixed;
        right: 20px;
        top: 10px;
        box-shadow: 2px 2px 10px 10px rgba(0, 0, 0, 0.111);
        border-radius: 8px;


        .switch_user,
        .suggested_user {
            display: flex;
            align-items: center;
            padding: 10px 20px;

            .profile_image {
                flex: 1;

                img {
                    width: 50px;
                    height: 50px;
                    border-radius: 50%;
                }
            }

            .profile_username {
                flex: 3;
                display: flex;
                flex-direction: column;
                gap: 3px;

               
                span{
                    color: grey;
                    font-size: 14px;
                }

                .username{
                    color: black;
                }

                span:first-child {
                    font-weight: 700;
                    font-size: 16px;       
                }
            }

            .cta {
                flex: 1;
                justify-content: right;
                display: flex;

                span {
                    color: rgb(108, 36, 171);
                    letter-spacing: 1px;
                    font-weight: 500;
                    cursor: pointer;
                }
            }

        }

        .suggesting_heading,
        .trending_heading {
            display: flex;
            justify-content: space-between;
            padding: 20px;

            span:first-child {
                font-size: 18px;
                font-weight: 700;
            }

            span:last-child {

                color: grey;
                font-weight: 600;
                cursor: pointer;
            }
        }
    }
</style>




<div class="suggestions">

    <div class="switch_user">

        <div class="profile_image">
            <img src="@Model?.LoggedInUser?.ProfilePic" />
        </div>

        <div class="profile_username">
            <span class="username"> @Model?.LoggedInUser?.Username </span>

            <span> #irfan33</span>
        </div>

        <div class="cta">

            <span> Switch </span>
        </div>

    </div>


    <div class="suggesting_heading">

        <span>Suggested For You</span>
        <span> See All</span>

    </div>

    @foreach (var user in Model.SuggestedUsers)
    {

        <div class="suggested_user">

            <div class="profile_image">
                <img src="@user.ProfilePic" />
            </div>



            <div class="profile_username">
                <span> @user.Username </span>

                <span> #dummyId</span>
            </div>


            <div class="cta">

                <span> Follow </span>
            </div>



        </div>

    }

    <div class="trending_heading">

        <span>Trending Artists</span>
        <span> See All</span>

    </div>


     @foreach (var user in Model.SuggestedUsers.Where(user => user.Posts.Count == 3))
    {

        <div class="suggested_user">

            <div class="profile_image">
                <img src="@user.ProfilePic" />
            </div>



            <div class="profile_username">
                <span> @user.Username </span>

                <span> #dummyId</span>
            </div>


            <div class="cta">

                <span> Follow </span>
            </div>



        </div>

    }



</div>

Views/Shared/_Layout.cshtml
@{
 User? user = Context.Items[key: "user"] as User;
}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData[index: "Title"] - Trinkle Buddies</title>

    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/P1WebMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>

<body>

@* 
<header>
  <!-- Navbar -->


  <nav class="navbar navbar-expand-lg bg-white border-bottom shadow-sm">
    <div class="container-fluid">

      <!-- Brand on the left -->
      <a class="navbar-brand fw-bold d-flex align-items-center" href="/">
        <i class="bi bi-stars me-2"></i> Trinkle Buddies
      </a>


      <!-- Navbar toggler for mobile -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSocialApp" aria-controls="navbarSocialApp" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <!-- Navbar links and account section -->
      <div class="collapse navbar-collapse" id="navbarSocialApp">



        <!-- Left side links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="/Explore"><i class="bi bi-compass"></i> Explore</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/reels"><i class="bi bi-camera-reels"></i> Reels</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/user/friends"><i class="bi bi-person"></i> Friends</a>
          </li>
        </ul>
        <!-- Right side account section -->



        @if(user != null){

      
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
          <li class="nav-item me-2">
            <a class="nav-link" href="/messages" title="Messages">
              <i class="bi bi-chat-dots fs-5"></i>
            </a>
          </li>
          <li class="nav-item me-2">
            <a class="nav-link" href="/notifications" title="Notifications">
              <i class="bi bi-bell fs-5"></i>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="navbarDropdownProfile" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="@user?.ProfilePic" alt="Profile" class="rounded-circle" width="32" height="32" style="object-fit:cover;">


              <span class="ms-2 fw-semibold"> 

                 @user?.Username

              </span>


            </a>


            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownProfile">
              <li><a class="dropdown-item " href="/user/Dashboard"><i class="bi bi-person"></i> My Profile</a></li>
              <li><a class="dropdown-item" href="/settings"><i class="bi bi-gear"></i> Settings</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="/user/login"><i class="bi bi-box-arrow-right"></i> Login</a></li>
              <li><a class="dropdown-item" href="/account/logout"><i class="bi bi-box-arrow-right"></i> Logout</a></li>
            </ul>
          </li>
        </ul>

         }


      </div>
    </div>
  </nav>
  <!-- Navbar -->
</header> *@


<div style="position: absolute; right : 0" >
    @{
        if (@TempData[key: "SuccessMessage"] != null)
        {

            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Success</strong> @TempData["SuccessMessage"]
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }


        if (@TempData[key: "ErrorMessage"] != null)
        {

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Error</strong> @TempData["ErrorMessage"]
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))
        {

            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Success</strong> @ViewBag.SuccessMessage
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
        {

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Error</strong> @ViewBag.ErrorMessage
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }
    }
</div>


         @RenderBody()
 



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Trinkle Buddies - <a asp-area="" asp-controller="Home" asp-action="Privacy">See our user Agreement & Privacy policy</a>
        </div>
    </footer>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync(name: "Scripts", required: false)
</body>

</html>